provider:
  name: openfaas
  gateway: https://faas.srv.disarm.io
functions:
  fn-village-finder:
    lang: r-geospatial
    handler: ./function
    image: disarm/fn-village-finder:0.1.0
    environment:
      write_debug: true
      exec_timeout: 600
      write_timeout: 700
      read_timeout: 700
      combine_output: false
    labels:
      com.openfaas.scale.zero: true
