provider:
  name: faas
  gateway: https://faas.srv.disarm.io
functions:
  fn-village-finder:
    lang: dockerfile
    handler: ./fn-village-finder
    image: disarm/fn-village-finder:0.0.1
    environment:
      write_debug: true
      exec_timeout: 60
      write_timeout: 70
      read_timeout: 70
      combine_output: false
